version: "3"
services:
  postgres:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: poor-pgdb
    volumes:
      # - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5432:5432"
    networks:
      - main_network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: webclient-dev
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
    networks:
      - main_network

  nestjs-api:
    build:
      context: server
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - Database__Host=${POSTGRES_HOST}
      - Database__Port=${POSTGRES_PORT}
      - Database__User=${POSTGRES_USER}
      - Database__Pass=${POSTGRES_PASSWORD}

    depends_on:
      - postgres
    volumes:
      - ./server/src:/app/src
    networks:
      - main_network

networks:
  main_network:
    driver: bridge

volumes:
  postgres-data:
